[package]
name = "jolt-sdk"
version = "0.1.0"
authors = [
    "Michael Zhu <mzhu@a16z.com>",
    "Sam Ragsdale <sragsdale@a16z.com>",
    "Noah Citron <ncitron@a16z.com>",
]
description = "SDK for Jolt"
license = "MIT"
homepage = "https://github.com/a16z/jolt/README.md"
repository = "https://github.com/a16z/jolt"
edition = "2021"

[features]
host = [
    "dep:tracer",
    "dep:common",
    "dep:jolt-core",
    "dep:ark-ec",
    "dep:ark-ff",
    "dep:ark-bn254",
    "dep:ark-serialize",
    "dep:eyre",
    "postcard/use-std",
]

guest-std = [
    "postcard/use-std",
    "serde/std",
    "jolt-sdk-macros/guest-std",
]

[dependencies]
postcard = { version = "1.0.8", default-features = false }
serde = { version = "1.0.196", default-features = false }
eyre = { version = "0.6.12", optional = true }
ark-ec = { version = "0.4.2", default-features = false, optional = true }
ark-ff = { version = "0.4.2", default-features = false, optional = true }
ark-bn254 = { version = "0.4.0", default-features = false, optional = true }
ark-serialize = { version = "0.4.2", features = ["derive"], optional = true }
base64 =  "0.22.0"

jolt-sdk-macros = { path = "./macros" }
jolt-core = { path = "../jolt-core", optional = true }
tracer = { path = "../tracer", optional = true }
common = { path = "../common", optional = true }
